# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/salaadas/Programming/slides

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/salaadas/Programming/slides

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/salaadas/Programming/slides/CMakeFiles /home/salaadas/Programming/slides//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/salaadas/Programming/slides/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

array.o: array.cpp.o
.PHONY : array.o

# target to build an object file
array.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/array.cpp.o
.PHONY : array.cpp.o

array.i: array.cpp.i
.PHONY : array.i

# target to preprocess a source file
array.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/array.cpp.i
.PHONY : array.cpp.i

array.s: array.cpp.s
.PHONY : array.s

# target to generate assembly for a file
array.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/array.cpp.s
.PHONY : array.cpp.s

audio.o: audio.cpp.o
.PHONY : audio.o

# target to build an object file
audio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/audio.cpp.o
.PHONY : audio.cpp.o

audio.i: audio.cpp.i
.PHONY : audio.i

# target to preprocess a source file
audio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/audio.cpp.i
.PHONY : audio.cpp.i

audio.s: audio.cpp.s
.PHONY : audio.s

# target to generate assembly for a file
audio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/audio.cpp.s
.PHONY : audio.cpp.s

bucket_array.o: bucket_array.cpp.o
.PHONY : bucket_array.o

# target to build an object file
bucket_array.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/bucket_array.cpp.o
.PHONY : bucket_array.cpp.o

bucket_array.i: bucket_array.cpp.i
.PHONY : bucket_array.i

# target to preprocess a source file
bucket_array.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/bucket_array.cpp.i
.PHONY : bucket_array.cpp.i

bucket_array.s: bucket_array.cpp.s
.PHONY : bucket_array.s

# target to generate assembly for a file
bucket_array.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/bucket_array.cpp.s
.PHONY : bucket_array.cpp.s

catalog.o: catalog.cpp.o
.PHONY : catalog.o

# target to build an object file
catalog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/catalog.cpp.o
.PHONY : catalog.cpp.o

catalog.i: catalog.cpp.i
.PHONY : catalog.i

# target to preprocess a source file
catalog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/catalog.cpp.i
.PHONY : catalog.cpp.i

catalog.s: catalog.cpp.s
.PHONY : catalog.s

# target to generate assembly for a file
catalog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/catalog.cpp.s
.PHONY : catalog.cpp.s

common.o: common.cpp.o
.PHONY : common.o

# target to build an object file
common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/common.cpp.o
.PHONY : common.cpp.o

common.i: common.cpp.i
.PHONY : common.i

# target to preprocess a source file
common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/common.cpp.i
.PHONY : common.cpp.i

common.s: common.cpp.s
.PHONY : common.s

# target to generate assembly for a file
common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/common.cpp.s
.PHONY : common.cpp.s

compiled_header_libs.o: compiled_header_libs.cpp.o
.PHONY : compiled_header_libs.o

# target to build an object file
compiled_header_libs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/compiled_header_libs.cpp.o
.PHONY : compiled_header_libs.cpp.o

compiled_header_libs.i: compiled_header_libs.cpp.i
.PHONY : compiled_header_libs.i

# target to preprocess a source file
compiled_header_libs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/compiled_header_libs.cpp.i
.PHONY : compiled_header_libs.cpp.i

compiled_header_libs.s: compiled_header_libs.cpp.s
.PHONY : compiled_header_libs.s

# target to generate assembly for a file
compiled_header_libs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/compiled_header_libs.cpp.s
.PHONY : compiled_header_libs.cpp.s

cursor.o: cursor.cpp.o
.PHONY : cursor.o

# target to build an object file
cursor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/cursor.cpp.o
.PHONY : cursor.cpp.o

cursor.i: cursor.cpp.i
.PHONY : cursor.i

# target to preprocess a source file
cursor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/cursor.cpp.i
.PHONY : cursor.cpp.i

cursor.s: cursor.cpp.s
.PHONY : cursor.s

# target to generate assembly for a file
cursor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/cursor.cpp.s
.PHONY : cursor.cpp.s

draw.o: draw.cpp.o
.PHONY : draw.o

# target to build an object file
draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/draw.cpp.o
.PHONY : draw.cpp.o

draw.i: draw.cpp.i
.PHONY : draw.i

# target to preprocess a source file
draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/draw.cpp.i
.PHONY : draw.cpp.i

draw.s: draw.cpp.s
.PHONY : draw.s

# target to generate assembly for a file
draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/draw.cpp.s
.PHONY : draw.cpp.s

events.o: events.cpp.o
.PHONY : events.o

# target to build an object file
events.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/events.cpp.o
.PHONY : events.cpp.o

events.i: events.cpp.i
.PHONY : events.i

# target to preprocess a source file
events.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/events.cpp.i
.PHONY : events.cpp.i

events.s: events.cpp.s
.PHONY : events.s

# target to generate assembly for a file
events.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/events.cpp.s
.PHONY : events.cpp.s

file_utils.o: file_utils.cpp.o
.PHONY : file_utils.o

# target to build an object file
file_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/file_utils.cpp.o
.PHONY : file_utils.cpp.o

file_utils.i: file_utils.cpp.i
.PHONY : file_utils.i

# target to preprocess a source file
file_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/file_utils.cpp.i
.PHONY : file_utils.cpp.i

file_utils.s: file_utils.cpp.s
.PHONY : file_utils.s

# target to generate assembly for a file
file_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/file_utils.cpp.s
.PHONY : file_utils.cpp.s

font.o: font.cpp.o
.PHONY : font.o

# target to build an object file
font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/font.cpp.o
.PHONY : font.cpp.o

font.i: font.cpp.i
.PHONY : font.i

# target to preprocess a source file
font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/font.cpp.i
.PHONY : font.cpp.i

font.s: font.cpp.s
.PHONY : font.s

# target to generate assembly for a file
font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/font.cpp.s
.PHONY : font.cpp.s

glad.o: glad.c.o
.PHONY : glad.o

# target to build an object file
glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/glad.c.o
.PHONY : glad.c.o

glad.i: glad.c.i
.PHONY : glad.i

# target to preprocess a source file
glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/glad.c.i
.PHONY : glad.c.i

glad.s: glad.c.s
.PHONY : glad.s

# target to generate assembly for a file
glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/glad.c.s
.PHONY : glad.c.s

hash.o: hash.cpp.o
.PHONY : hash.o

# target to build an object file
hash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/hash.cpp.o
.PHONY : hash.cpp.o

hash.i: hash.cpp.i
.PHONY : hash.i

# target to preprocess a source file
hash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/hash.cpp.i
.PHONY : hash.cpp.i

hash.s: hash.cpp.s
.PHONY : hash.s

# target to generate assembly for a file
hash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/hash.cpp.s
.PHONY : hash.cpp.s

hotloader.o: hotloader.cpp.o
.PHONY : hotloader.o

# target to build an object file
hotloader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/hotloader.cpp.o
.PHONY : hotloader.cpp.o

hotloader.i: hotloader.cpp.i
.PHONY : hotloader.i

# target to preprocess a source file
hotloader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/hotloader.cpp.i
.PHONY : hotloader.cpp.i

hotloader.s: hotloader.cpp.s
.PHONY : hotloader.s

# target to generate assembly for a file
hotloader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/hotloader.cpp.s
.PHONY : hotloader.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cpp.s
.PHONY : main.cpp.s

newstring.o: newstring.cpp.o
.PHONY : newstring.o

# target to build an object file
newstring.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/newstring.cpp.o
.PHONY : newstring.cpp.o

newstring.i: newstring.cpp.i
.PHONY : newstring.i

# target to preprocess a source file
newstring.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/newstring.cpp.i
.PHONY : newstring.cpp.i

newstring.s: newstring.cpp.s
.PHONY : newstring.s

# target to generate assembly for a file
newstring.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/newstring.cpp.s
.PHONY : newstring.cpp.s

opengl.o: opengl.cpp.o
.PHONY : opengl.o

# target to build an object file
opengl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/opengl.cpp.o
.PHONY : opengl.cpp.o

opengl.i: opengl.cpp.i
.PHONY : opengl.i

# target to preprocess a source file
opengl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/opengl.cpp.i
.PHONY : opengl.cpp.i

opengl.s: opengl.cpp.s
.PHONY : opengl.s

# target to generate assembly for a file
opengl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/opengl.cpp.s
.PHONY : opengl.cpp.s

path_utils.o: path_utils.cpp.o
.PHONY : path_utils.o

# target to build an object file
path_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/path_utils.cpp.o
.PHONY : path_utils.cpp.o

path_utils.i: path_utils.cpp.i
.PHONY : path_utils.i

# target to preprocess a source file
path_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/path_utils.cpp.i
.PHONY : path_utils.cpp.i

path_utils.s: path_utils.cpp.s
.PHONY : path_utils.s

# target to generate assembly for a file
path_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/path_utils.cpp.s
.PHONY : path_utils.cpp.s

pool.o: pool.cpp.o
.PHONY : pool.o

# target to build an object file
pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/pool.cpp.o
.PHONY : pool.cpp.o

pool.i: pool.cpp.i
.PHONY : pool.i

# target to preprocess a source file
pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/pool.cpp.i
.PHONY : pool.cpp.i

pool.s: pool.cpp.s
.PHONY : pool.s

# target to generate assembly for a file
pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/pool.cpp.s
.PHONY : pool.cpp.s

shader_catalog.o: shader_catalog.cpp.o
.PHONY : shader_catalog.o

# target to build an object file
shader_catalog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shader_catalog.cpp.o
.PHONY : shader_catalog.cpp.o

shader_catalog.i: shader_catalog.cpp.i
.PHONY : shader_catalog.i

# target to preprocess a source file
shader_catalog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shader_catalog.cpp.i
.PHONY : shader_catalog.cpp.i

shader_catalog.s: shader_catalog.cpp.s
.PHONY : shader_catalog.s

# target to generate assembly for a file
shader_catalog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shader_catalog.cpp.s
.PHONY : shader_catalog.cpp.s

slides.o: slides.cpp.o
.PHONY : slides.o

# target to build an object file
slides.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/slides.cpp.o
.PHONY : slides.cpp.o

slides.i: slides.cpp.i
.PHONY : slides.i

# target to preprocess a source file
slides.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/slides.cpp.i
.PHONY : slides.cpp.i

slides.s: slides.cpp.s
.PHONY : slides.s

# target to generate assembly for a file
slides.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/slides.cpp.s
.PHONY : slides.cpp.s

table.o: table.cpp.o
.PHONY : table.o

# target to build an object file
table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/table.cpp.o
.PHONY : table.cpp.o

table.i: table.cpp.i
.PHONY : table.i

# target to preprocess a source file
table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/table.cpp.i
.PHONY : table.cpp.i

table.s: table.cpp.s
.PHONY : table.s

# target to generate assembly for a file
table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/table.cpp.s
.PHONY : table.cpp.s

texture_catalog.o: texture_catalog.cpp.o
.PHONY : texture_catalog.o

# target to build an object file
texture_catalog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/texture_catalog.cpp.o
.PHONY : texture_catalog.cpp.o

texture_catalog.i: texture_catalog.cpp.i
.PHONY : texture_catalog.i

# target to preprocess a source file
texture_catalog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/texture_catalog.cpp.i
.PHONY : texture_catalog.cpp.i

texture_catalog.s: texture_catalog.cpp.s
.PHONY : texture_catalog.s

# target to generate assembly for a file
texture_catalog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/texture_catalog.cpp.s
.PHONY : texture_catalog.cpp.s

time_info.o: time_info.cpp.o
.PHONY : time_info.o

# target to build an object file
time_info.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/time_info.cpp.o
.PHONY : time_info.cpp.o

time_info.i: time_info.cpp.i
.PHONY : time_info.i

# target to preprocess a source file
time_info.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/time_info.cpp.i
.PHONY : time_info.cpp.i

time_info.s: time_info.cpp.s
.PHONY : time_info.s

# target to generate assembly for a file
time_info.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/time_info.cpp.s
.PHONY : time_info.cpp.s

user_control.o: user_control.cpp.o
.PHONY : user_control.o

# target to build an object file
user_control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/user_control.cpp.o
.PHONY : user_control.cpp.o

user_control.i: user_control.cpp.i
.PHONY : user_control.i

# target to preprocess a source file
user_control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/user_control.cpp.i
.PHONY : user_control.cpp.i

user_control.s: user_control.cpp.s
.PHONY : user_control.s

# target to generate assembly for a file
user_control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/user_control.cpp.s
.PHONY : user_control.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... game"
	@echo "... array.o"
	@echo "... array.i"
	@echo "... array.s"
	@echo "... audio.o"
	@echo "... audio.i"
	@echo "... audio.s"
	@echo "... bucket_array.o"
	@echo "... bucket_array.i"
	@echo "... bucket_array.s"
	@echo "... catalog.o"
	@echo "... catalog.i"
	@echo "... catalog.s"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... compiled_header_libs.o"
	@echo "... compiled_header_libs.i"
	@echo "... compiled_header_libs.s"
	@echo "... cursor.o"
	@echo "... cursor.i"
	@echo "... cursor.s"
	@echo "... draw.o"
	@echo "... draw.i"
	@echo "... draw.s"
	@echo "... events.o"
	@echo "... events.i"
	@echo "... events.s"
	@echo "... file_utils.o"
	@echo "... file_utils.i"
	@echo "... file_utils.s"
	@echo "... font.o"
	@echo "... font.i"
	@echo "... font.s"
	@echo "... glad.o"
	@echo "... glad.i"
	@echo "... glad.s"
	@echo "... hash.o"
	@echo "... hash.i"
	@echo "... hash.s"
	@echo "... hotloader.o"
	@echo "... hotloader.i"
	@echo "... hotloader.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... newstring.o"
	@echo "... newstring.i"
	@echo "... newstring.s"
	@echo "... opengl.o"
	@echo "... opengl.i"
	@echo "... opengl.s"
	@echo "... path_utils.o"
	@echo "... path_utils.i"
	@echo "... path_utils.s"
	@echo "... pool.o"
	@echo "... pool.i"
	@echo "... pool.s"
	@echo "... shader_catalog.o"
	@echo "... shader_catalog.i"
	@echo "... shader_catalog.s"
	@echo "... slides.o"
	@echo "... slides.i"
	@echo "... slides.s"
	@echo "... table.o"
	@echo "... table.i"
	@echo "... table.s"
	@echo "... texture_catalog.o"
	@echo "... texture_catalog.i"
	@echo "... texture_catalog.s"
	@echo "... time_info.o"
	@echo "... time_info.i"
	@echo "... time_info.s"
	@echo "... user_control.o"
	@echo "... user_control.i"
	@echo "... user_control.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

